### ISSUE TITLE
Problem with Windows if it runs wrong operating system like it doesn't know my Windows 10

### ISSUE THREAD

**Issue by sourceskyboxer** [Nihlus/GLWidgetTest#2]
Hello everyone, 

please explain me!

Why does it happen if I am using Windows 10 Pro x64 and your GtkWidgetTest can not run because it throws error it uses only X11 Linux. What does it mean? Hello my Windows is not linux just my Windows 10 is Windows.

How do I fix?

```
OpenTK running on windows
Managed Debugging Assistant 'PInvokeStackImbalance' 
A call to PInvoke function 'GLWidget!OpenTK.GLWidget::gdk_win32_drawable_get_handle' has unbalanced the stack. This is likely because the managed PInvoke signature does not match the unmanaged target signature. Check that the calling convention and parameters of the PInvoke signature match the target unmanaged signature.

'GLWidgetTestGTK3.exe' (CLR v4.0.30319: GLWidgetTestGTK3.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.ArgumentException: window
Parameter name: Must be a valid window.
   at OpenTK.Platform.Windows.WinGLContext..ctor(GraphicsMode format, WinWindowInfo window, IGraphicsContext sharedContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Platform.Windows.WinFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run()
   at GLWidgetTestGTK3.MainClass.Main(String[] args)


(GLWidgetTestGTK3:20320): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'
```

I have tried.... No success...

**Comment by Nihlus** [comment]
This project is generally unmaintained - however, that error is due to a missing function in the GTK# libraries in use, or a malformed P/Invoke declaration. The latest version from the OpenTK repository uses a more modern version of the GTK# libraries.

This is not the case on Linux, where the libraries are compiled and deployed correctly.
